export { default as Global } from './Global'
export { default as Menu } from './Menu'
export { default as Tasks } from './Tasks'
export { default as Shortcuts } from './Shortcuts'
export { default as Paid } from './Paid'
export { default as About } from './About'
