import '@/styles/katex/index.global.css'
import '@/styles/class.global.css'
import '@/styles/contexify.default.global.css'
import '@/styles/contexify.global.css'
import '@/styles/emoji.global.css'
import '@/styles/react-horizontal-scrolling-menu.global.css'
import '@/styles/vars.global.css'
import '@/theme/custom/antd.global.css'
import '@/styles/xyflow.global.css'
import '@/styles/editor.global.css'
import '@/styles/shiki.global.css'

