export { default as getLang } from './getLang'
export { default as id } from './id'
export { default as sleep } from './sleep'
export { default as setFavicon } from './setFavicon'
export { default as setGlobalAnimation } from './setGlobalAnimation'
export { default as setStorageWhenChange } from './setStorageWhenChange'

export * from './is'
export * from './filter'
export * from './rxdb'
